export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FETCH_FULLPOST_START = 'FETCH_FULLPOST_START';
export const FETCH_FULLPOST_SUCCESS = 'FETCH_FULLPOST_SUCCESS';
export const FETCH_FULLPOST_FAIL = 'FETCH_FULLPOST_FAIL';

export const DELETE_FULLPOST_START = 'DELETE_FULLPOST_START';
export const DELETE_FULLPOST_SUCCESS = 'DELETE_FULLPOST_SUCCESS';
export const DELETE_FULLPOST_FAIL = 'DELETE_FULLPOST_FAIL';

export const NEW_POST_START = 'NEW_POST_START';
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_FAIL = 'NEW_POST_FAIL';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';

export const SLAP_STATUS = 'SLAP_STATUS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';